# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Serve < Formula
  desc "Public tunnel for hosted serve accounts"
  homepage "https://github.com/swyftlabs/serve"
  version "0.8.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/servelink-swyftlabs/serve-dist/releases/download/v0.8.1/serve_0.8.1_darwin_amd64.tar.gz"
      sha256 "a485653b0f8913875d0e431180ee8cbdfd013facd009d5d4f128d055e551da02"

      define_method(:install) do
        bin.install "serve"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/servelink-swyftlabs/serve-dist/releases/download/v0.8.1/serve_0.8.1_darwin_arm64.tar.gz"
      sha256 "0e70615095bbfab70799106502a3169c150a064029723c62fe19c5e77da9e014"

      define_method(:install) do
        bin.install "serve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/servelink-swyftlabs/serve-dist/releases/download/v0.8.1/serve_0.8.1_linux_amd64.tar.gz"
      sha256 "cd7d066c18ccc3c143c8579f893a48fb4418d179bc78fb63e22a18f9e6769fbf"
      define_method(:install) do
        bin.install "serve"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/servelink-swyftlabs/serve-dist/releases/download/v0.8.1/serve_0.8.1_linux_arm64.tar.gz"
      sha256 "1482d8f5ac0c95edf04accc48bf54874f32e473cb8e4ee412ad4ea5324623d92"
      define_method(:install) do
        bin.install "serve"
      end
    end
  end
end
